spring:
  application:
    name: SwiftAPI
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://db:5432/compose-postgres
    username: compose-postgres
    password: compose-postgres

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json


logging:
  level:
    org:
      springframework:
        web: debug
    web: debug